%{
int num = 0;
%}
%%
[A] printf("4");
[B] printf("13");
[C] printf("(");
[D] printf("[)");
[E] printf("3");
[F] printf("|=");
[G] printf("6");
[H] printf("|-|");
[I] printf("|");
[J] printf(".]");
[K] printf("|<");
[L] printf("1");
[M] printf("|Y|");
[N] printf("/|/");
[O] printf("0");
[P] printf("|>");
[Q] printf("0,");
[R] printf("|2");
[S] printf("5");
[T] printf("7");
[U] printf("[_]");
[V] printf("|/");
[W] printf("|/|/");
[X] printf("}{");
[Y] printf("'/");
%%